<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.ri9o65A' shared service.

return $this->privates['.service_locator.ri9o65A'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'dernek' => ['privates', '.errored..service_locator.ri9o65A.App\\Entity\\Dernek', NULL, 'Cannot autowire service ".service_locator.ri9o65A": it references class "App\\Entity\\Dernek" but no such service exists.'],
], [
    'dernek' => 'App\\Entity\\Dernek',
]);
