<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.niLy2Or' shared service.

return $this->privates['.service_locator.niLy2Or'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'dernek' => ['privates', '.errored..service_locator.niLy2Or.App\\Entity\\Dernek', NULL, 'Cannot autowire service ".service_locator.niLy2Or": it references class "App\\Entity\\Dernek" but no such service exists.'],
    'dernekRepository' => ['privates', 'App\\Repository\\DernekRepository', 'getDernekRepositoryService.php', true],
    'imageRepository' => ['privates', 'App\\Repository\\ImageRepository', 'getImageRepositoryService.php', true],
], [
    'dernek' => 'App\\Entity\\Dernek',
    'dernekRepository' => 'App\\Repository\\DernekRepository',
    'imageRepository' => 'App\\Repository\\ImageRepository',
]);
