<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator..7T1Xms' shared service.

return $this->privates['.service_locator..7T1Xms'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'dernekRepository' => ['privates', 'App\\Repository\\DernekRepository', 'getDernekRepositoryService.php', true],
    'settingRepository' => ['privates', 'App\\Repository\\SettingRepository', 'getSettingRepositoryService.php', true],
], [
    'dernekRepository' => 'App\\Repository\\DernekRepository',
    'settingRepository' => 'App\\Repository\\SettingRepository',
]);
