<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.gSFBufQ' shared service.

return $this->privates['.service_locator.gSFBufQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'setting' => ['privates', '.errored..service_locator.gSFBufQ.App\\Entity\\Setting', NULL, 'Cannot autowire service ".service_locator.gSFBufQ": it references class "App\\Entity\\Setting" but no such service exists.'],
], [
    'setting' => 'App\\Entity\\Setting',
]);
