<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXa8Ohxc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXa8Ohxc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXa8Ohxc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXa8Ohxc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXa8Ohxc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Xa8Ohxc',
    'container.build_id' => '9cda7350',
    'container.build_time' => 1579110530,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXa8Ohxc');
